swagger: '2.0'
info:
  description: This is the endpoint api for ldm solutions
  version: 1.0.0
  title: LDM API
schemes:
 - https
produces:
  - application/json
x-google-backend: 
  address: https://ldm-api-prod-qu3sicvmsa-uc.a.run.app
paths:
  /predict:
    post:
      consumes: 
        - "multipart/form-data"
      summary: returs a prediction of the image uploaded
      operationId: predict
      security:
          - api_key: []
      parameters: [{name: file, in: formData, description: file, required: true, type: string, format: binary}]
      responses:
        200:
          description: Prediction ok
          examples:
            application/json:
              data:
                id: 1
                nombre: pitanga
                descripcion: Eugenia uniflora
        400:
          description: bad request
          examples:
            application/json:
              data:
                id: 500
                nombre: ""
                descripcion: Formato no compatible. Usar jpg o jpeg.
        413:
          description: file too big
          examples:
            application/json:
              data:
                id: 500
                nombre: ""
                descripcion: Archivo muy grande. Debe ser menor a 16 mb.
        
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"

