swagger: '2.0'
info:
  description: This is the endpoint api for ldm solutions
  version: 1.0.0
  title: LDM API
schemes:
 - https
produces:
  - application/json
x-google-backend: 
  address: https://ldm-api-prod-qu3sicvmsa-uc.a.run.app
paths:
  /predict:
    post:
      summary: returs a prediction of the image uploaded
      operationId: predict
      security:
          - api_key: []
      parameters: [{name: file, in: formData, description: file, required: true, type: string, format: binary}]
      responses:
        200:
          description: Ok
        400:
          description: invalid input, object invalid
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"

